name: pixelboost
description: Uses the SRCNN to perform single image super-resolution.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^3.0.0
  dio: ^4.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/Raleway-Black.ttf